[project]
name = "build-agent-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=0.3.20",
    "langchain-core>=0.3.41",
    "openai>=1.65.4",
    "python-dotenv>=1.0.1",
]
